version: 1
incremental: false
disable_existing_loggers: false

formatters:
    default:
        format: "%(asctime)s %(levelname)-8s [%(name)s]: %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
    console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
        stream: ext://sys.stderr

root:
    level: DEBUG
    handlers:
        - console

loggers: {}
